export PATH="/usr/local/bin:$PATH"

# Path to the bash it configuration
export BASH_IT="/Users/$(whoami)/.bash_it"

# Lock and Load a custom theme file
export BASH_IT_THEME="bobby"

# Load Bash It
source $BASH_IT/bash_it.sh

# Unified bash history
# Source: https://superuser.com/a/734410
shopt -s histappend
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# Load FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

source "/opt/homebrew/share/google-cloud-sdk/completion.bash.inc"
source "/opt/homebrew/share/google-cloud-sdk/path.bash.inc"

eval "$(/opt/homebrew/bin/brew shellenv)"

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return ;;
esac