#!/usr/bin/env bash

set -e

if [[ "$SHELL" == *"zsh"* ]] ; then
  cat <<-EOF

!! WARNING: 'zsh' detected.

'zsh' is the default shell, starting with macOS catalina.
However, this install script is intended to be ran in bash.
You can change the default shell type to bash by:
  1) Running 'chsh -s /bin/bash'
  2) Closing & reopening iTerm

EOF
  exit 1
fi

DIR="$(dirname "${BASH_SOURCE[0]}")"

for file in $DIR/install-scripts/*; do
  if [ ! -d ./$file ]; then
    ./$file
  fi
done
